# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle dependencies

      - run: gradle displayCommitHash

      - run: gradle buildPlugin

      - store_artifacts:
          path: build/distributions

      - run: gradle test --info
